{
 "title": "New dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Host",
    "query": "import \"influxdata/influxdb/schema\"\n\nschema.tagValues(\n    bucket: \"5gm\",\n    tag: \"host\",\n    predicate: (r) => r._measurement == \"statistic\",\n    start: -3000d\n)"
   }
  ]
 },
 "panels": [
  {
   "title": "StatisticSystem",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket:\"5gm\")\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n|> filter(fn: (r) => r._measurement == \"StatisticSystem\" and r._field == \"cpu\" and r.host =~ /${Host:regex}/)\n\n"
    }
   ]
  },
  {
   "title": "Scheduler count operation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "query": "from(bucket:\"5gm\")\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n|> filter(fn: (r) => r._measurement == \"Scheduler\" and r._field == \"count\" and r.host =~ /${Host:regex}/)"
    }
   ]
  },
  {
   "title": "Scheduler Operation time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "query": "from(bucket:\"5gm\")\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n|> filter(fn: (r) => r._measurement == \"Scheduler\" and (r._field == \"averageTime\" or r._field == \"maxTime\" or r._field == \"sumTime\") and r.host =~ /${Host:regex}/)"
    }
   ]
  }
 ]
}